

services:
  db:
    container_name: spend-track-db
    image: postgres:16.10
    volumes:
      - spend-track-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432

volumes:
  spend-track-data:
